name: Release

on:
  push:
    tags:
      - '*'

jobs:
  aliddns:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20.0'
      - name: Install Snapcraft
        run: |
          sudo snap install snapcraft --classic
          echo ${{ secrets.SNAPCRAFT_TOKEN }} | snapcraft login --with -
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: openiothub
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
